---
title: Data Visualization
author:
- name: Kieran Healy
  affiliation: Duke University
  email: kjhealy@soc.duke.edu
date: Fall 2015
...

```{r Cleanup, include=FALSE, cache=FALSE}

read_chunk("setup/clean-up.r")

```

```{r Setup, include=FALSE, results="hide", warning=FALSE}
opts_chunk$set(fig.path="figures/fig-",
               cache.path="cache/working-",
               dev=c("png","pdf"),
               fig.width=14,
               fig.height=7,
               dpi=300,
               fig.show="hold",
               fig.lp="fig:",
               cache=TRUE,
               par=TRUE,
               message=FALSE,
               warning=FALSE)

knit_hooks$set(par = function(before, options, envir){
    if (before && options$fig.show!='none') par(mar=c(4,4,.1,.1),
                                                cex.lab=.95,
                                                cex.axis=.9,
                                                mgp=c(2,.7,0),
                                                tcl=-.3)
}, crop=hook_pdfcrop)

opts_knit$set(kfigr.prefix=TRUE,
              kfigr.link=FALSE)

```

```{r Options}

source("setup/options-and-libraries.r")

```

# Introduction
This half-semester course is an introduction to some principles and methods of data visualization. It is aimed at graduate students in the Sociology department.

```{r Cars}

head(mtcars)

p <- ggplot(data=mtcars, aes(x=wt, y=mpg, color=factor(cyl)))
p + geom_point()

```

# Week 1

# Week 2

# Week 3


